apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    name: booking-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      component: booking-service
  template:
    metadata:
      labels:
        component: booking-service
    spec:
      containers:
        - image: gcr.io/b2-microservices/booking-s-docker
          name: booking-service
          ports:
            - containerPort: 8090
              name: booking-service
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8200
            timeoutSeconds: 5
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8200
            timeoutSeconds: 5
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 5